export const RECORD_USERINFO = 'RECORD_USERINFO'
export const RECORD_DECLARE = 'RECORD_DECLARE'
export const AUTO_ROUTE = 'AUTO_ROUTE'
export const OUT_LOGIN = 'OUT_LOGIN'
export const TOUSU_DATA = 'TOUSU_DATA'
export const QUANJU_TAN = 'QUANJU_TAN'
export const QUANJU_BUTAN = 'QUANJU_BUTAN'
export const WECHAT = 'WECHAT'
export const WECHAT_DEL = 'WECHAT_DEL'

